### ISSUE TITLE
P3 implementing details

### ISSUE THREAD

**Issue by terry489490** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#14]
請問我該在CurRow.js 跟 Row.js 實作輸入的內容嗎
或是只需印出對應的資料

**Comment by anitalu724** [comment]
TODO3 請去CurRow.js 和 Row.js 裡面實作相關內容

請勿自行新增檔案，or 在非CurRow.js 和 Row.js 的檔案中實作 TODO3

**Comment by b09901134** [comment]
想請問按下Enter後要有反應也是要實作的部分嗎？

**Comment by ba144220** [comment]
@b09901134 你的反應是指？

**Comment by chinyi0523** [comment]
> 想請問按下Enter後要有反應也是要實作的部分嗎？

請見考試的Readme自行判斷他在哪個todo

**Comment by zih-ya** [comment]
TODO 3提到要"display the corresponding color"，但沒有看到Row.js, CurRow.js有引入正確答案，這樣要如何比對然後判定顏色是gray, green, 或是yellow呢？

**Comment by anitalu724** [comment]
此為考試內容，涉及答案討論，此issue將關閉，同學請自行思考，助教無法提供任何Hint。

**Comment by ba144220** [comment]
@zih-ya 可以看 `cypress/e2e/public.cy.js` ，第三題還不會測試顏色（但第四題會
