### ISSUE TITLE
2-2-2 CurRow is at the first row

### ISSUE THREAD

**Issue by qaz159qaz159** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#16]
我用第n次，currow undex為n-1的方式實作，但test的結果都會錯，請問是我的理解錯誤嗎

**Comment by qaz159qaz159** [comment]
打錯是currow index

**Comment by anitalu724** [comment]
@qaz159qaz159 
turn 是0~5的整數
不確定你的n定義為何

只能說CurRow的index 也是從0~5 會根據你目前所在的turn而定
