### ISSUE TITLE
Multiple Lines Test

### ISSUE THREAD

**Issue by weiiiii0622** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#17]
What should it possible be wrong for getting 
4.4) Multiple Lines Test (4.0/13.0)
5.2) Multiple Lines (4.0/12.0)
while other tests passed?
Or may I ask what does these testcases contain? (The format, or the testing point for these testcases...)

**Comment by chinyi0523** [comment]
> What should it possible be wrong for getting 4.4) Multiple Lines Test (4.0/13.0) 5.2) Multiple Lines (4.0/12.0) while other tests passed? Or may I ask what does these testcases contain? (The format, or the testing point for these testcases...)

Some of the testcases are correct. Please check 4.4 and 5.2
TA will not provide hints about hidden testcases
