### ISSUE TITLE
submit problem

### ISSUE THREAD

**Issue by andy0314** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#19]
我目前已經將board和keyboard做完了，也成功於畫面顯示，然而submit過後卻是0分，因此想請問壓縮方式等等原因是否會影響到上傳時判定的正確性。

**Comment by chinyi0523** [comment]
> 我目前已經將board和keyboard做完了，也成功於畫面顯示，然而submit過後卻是0分，因此想請問壓縮方式等等原因是否會影響到上傳時判定的正確性。

請問他跑完了嗎？0分有可能是正在評分
壓縮成zip上傳即可

**Comment by andy0314** [comment]
已跑完

**Comment by andy0314** [comment]
![image](https://user-images.githubusercontent.com/70873793/196325846-5f33ad0c-cbd1-442c-8b3a-7b87cc45431e.png)

**Comment by anitalu724** [comment]
請將整個src壓縮成src.zip

macOS / Linux 請用README.md上提供的指令
Windows 可以用按右鍵壓縮

請不要將整個hack1壓縮喔

**Comment by anitalu724** [comment]
@andy0314  另想問你是否有成功跑過cypress public test

如果沒有，很有可能你implement的方式本身有問題

**Comment by andy0314** [comment]
我只有壓縮src資料夾

**Comment by chinyi0523** [comment]
同學你是不是傳到作業四了

**Comment by andy0314** [comment]
是的，剛剛發現了，非常抱歉

**Comment by petrus1732** [comment]
我todo1已經能顯示keyBoard，但是上傳到gradescope怎麼傳都是0分，我有傳壓縮的src檔案，也沒傳到作業4，想知道有沒有可能是其他技術問題？
