### ISSUE TITLE
3-1與3-2題意詢問

### ISSUE THREAD

**Issue by NTUBOY** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#20]
我的第四個TODO全過了，跑起來也是正常，但3-1和3-2還是沒過。請問只要可以打到第二行，且輸入的字母當下會顯示在螢幕上就算過這兩關了對嗎?

**Comment by anitalu724** [comment]
如果沒有顯示在螢幕上->一定不會過
有顯示在螢幕上->不一定會過

可能是你implement的方式有誤、或不符合規格，請自行檢查，助教無法提供debug服務。
