### ISSUE TITLE
submit problem

### ISSUE THREAD

**Issue by Str367** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#22]
已經將keyboard跟board做完了
但是傳上去的時候卻都沒過

**Comment by joshmtlau** [comment]
同學你好，
請問你有在 local 跑過 cypress test 嗎？
如果你在 local 也沒有過，那極有可能是 implement 方法有問題或不符合 spec

**Comment by Str367** [comment]
![image](https://user-images.githubusercontent.com/96676102/196328554-3a21299a-0a0a-47f8-84ef-e3e2ceeb69f1.png)
沒有全過但也沒有像judhe那樣全都沒過

**Comment by CHENPINCHIEH** [comment]
我也是，在畫面上有呈現正確，但結果呈現：
1.2.1) Keyboard-container first row correct (0.0/6.0)
1.2.2) Keyboard-container second row correct (0.0/6.0)
怎麼辦？？

**Comment by ric2k1** [comment]
有按照指示正確上傳 src.zip 嗎？

**Comment by CHENPINCHIEH** [comment]
有的，2-1 2-1～都過了，發現這個沒過

<img width="587" alt="截圖 2022-10-18 上午11 32 24" src="https://user-images.githubusercontent.com/62798153/196329307-0a5c2617-5b20-42dc-a87a-9723b89a5ed6.png">

**Comment by joshmtlau** [comment]
@CHENPINCHIEH 既然 local 有部分測試通過，
目前猜測是 #9 ，請嘗試在 Gradescope rerun 看看

**Comment by Str367** [comment]
好他突然可以運作了@@

**Comment by joshmtlau** [comment]
Gradescope 有時會有突發不穩定情形，既然 local 有部分測試通過，
目前猜測是 #9 ，在 Gradescope rerun 可能就會修復
