### ISSUE TITLE
P5 char color & P6 string format

### ISSUE THREAD

**Issue by TranquilRock** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#25]
P5: assuming a yellow char 'a' is guessed in turn 0 and but not guessed in turn 1, shall it be displayed grey or yellow during turn 2?
P6: the default value of `result` seems to have extra " compare to the GIF on HackMD, are they both acceptable? 
P6: what tag should be used for displaying the result string.

**Comment by ba144220** [comment]
P5: yellow
P6: 以HackMD為主
P6: 確認className符合規範就好

**Comment by anitalu724** [comment]
P5: Please see the example provided in the video.
P6: You have some misunderstandings. Please find out yourself.
This issue is being closed. Some answers have been revealed here.
