### ISSUE TITLE
Wouldn't set delete more than one letter?

### ISSUE THREAD

**Issue by patrick7166** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#27]
Ex. solution = "happy"
if I guess "wepip", and delete the first p, which is green, from my solution set, the set becomes [h, a, y].
How do I find yellow letters after this? Or am I reading the TODOs wrong?

**Comment by anitalu724** [comment]
You have some misunderstandings. Please find out yourself. TA cannot give you any hint.
This issue is being closed. Some answers have been revealed here.
