### ISSUE TITLE
P3 id format

### ISSUE THREAD

**Issue by TranquilRock** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#38]
is the id of each entry '1-1'  or '1_1' or not even string type? 
the display looks normal, but autograding on gradescope gives all zeros.
![image](https://user-images.githubusercontent.com/23418421/196333920-8734adca-4e73-41ff-a60b-9cef67678a15.png)

**Comment by anitalu724** [comment]
請用string，README.md裡的pic都寫得很清楚，長得不一樣就是錯的
