### ISSUE TITLE
No package.json or package_lock.json file in hack1.zip

### ISSUE THREAD

**Issue by AlexLu0419** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#6]
I can't find my package.json file or package_lock.json file anywhere.
<img width="770" alt="截圖 2022-10-18 上午9 29 42" src="https://user-images.githubusercontent.com/97040881/196314287-1a7ca8e4-5662-44d0-8042-223635829e0b.png">

**Comment by anitalu724** [comment]
see #5 for detailed.
