### ISSUE TITLE
Could not find a required file.   Name: index.html   Searched in: /Users/mac/Documents/GitHub/wp1111/hack1/public

### ISSUE THREAD

**Issue by CHENPINCHIEH** [ntuee-web-programming/111-1_WebProgramming-Hack1_QA#8]
按下npm start 出現以下訊息：
Could not find a required file.
  Name: index.html
  Searched in: [/Users/mac/Documents/GitHub/wp1111/hack1/public[](url)]([url](url))
<img width="451" alt="截圖 2022-10-18 上午9 37 52" src="https://user-images.githubusercontent.com/62798153/196315204-81fa4d48-32b8-4739-aa63-bed4010d41f8.png">

**Comment by anitalu724** [comment]
@CHENPINCHIEH 請問你的public folder裡面有東西嗎？這張截圖看不見。

**Comment by CHENPINCHIEH** [comment]
yes, its ok now, i just drag json files in inner file hack1, structure issue
